/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import com.sun.java.swing.plaf.windows.resources.windows;
import java.awt.Font;
import java.util.Arrays;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.ir.Symbol;
import model.*;


/**
 *
 * @author Krist
 */
public class SpielGUI extends JFrame {
    
    Spiel spiel;
    Vector<Spieler> allespieler1;
    Vector<JButton> kartenButtons = new Vector<JButton>();
    Vector<String> kartenIds;
    Karte ausgewählteKarte;
    int index = 0;
    /**
     * Creates new form SpielGUI
     */
    public SpielGUI() {
        
    }

    SpielGUI(Vector<Spieler> allespieler) {
        initComponents();
        spiel = new Spiel(allespieler);
        spiel.rundeStarten();
        buttonsVector();
        setNameAktuellerSpieler();
        setButtonIcons();
        setjAblageStapelButton();
        //ausgewählteKarte = new Karte(ausgewählteKarte.getSymbol(),ausgewählteKarte.getZahl());
    }
    public void setSpielerPunkte(){
        int i = spiel.getAktuellerSpieler().getPunktezahl();
        String str = String.valueOf(i);
       jPunkteSpielerLabel.setText(str);
    }
    public void setButtonIcons(){
        String listString = spiel.getAktuellerSpieler().getSpielerHand().stream().map(Object::toString).collect(Collectors.joining(","));
        String[] kartenNamen = listString.split(",");
        kartenIds = new Vector<>();
        kartenIds.addAll(Arrays.asList(kartenNamen));
        for (int i = 0; i <spiel.getAktuellerSpieler().getSpielerHand().size(); i++) {
            kartenButtons.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("../images/"+spiel.getAktuellerSpieler().getSpielerHand().get(i).getSymbol()+" "+spiel.getAktuellerSpieler().getSpielerHand().get(i).getZahl()+ ".gif")));
        }
        for (int i = kartenIds.size(); i < kartenButtons.size(); i++) {
            kartenButtons.get(i).setIcon(null);
        }
    }

    public void buttonsVector(){
        kartenButtons.add(jButton1);
        kartenButtons.add(jButton2);
        kartenButtons.add(jButton3);
        kartenButtons.add(jButton4);
        kartenButtons.add(jButton5);
        kartenButtons.add(jButton6);
        kartenButtons.add(jButton7);
        kartenButtons.add(jButton8);
        kartenButtons.add(jButton9);
        kartenButtons.add(jButton10);
        kartenButtons.add(jButton11);
        kartenButtons.add(jButton12);
        kartenButtons.add(jButton13);
        kartenButtons.add(jButton14);
           
    }
    public void setNameAktuellerSpieler(){
        jAktuellerSpielerLabel.setText(spiel.getAktuellerSpieler().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jAktuellerSpielerLabel = new JLabel();
        jPunkteSpielerLabel = new JLabel();
        legenButton = new JButton();
        ziehenButton = new JButton();
        seppSagenButton = new JButton();
        tschauSagenButton = new JButton();
        jAblageStapelButton = new JButton();
        jButton1 = new JButton();
        jButton2 = new JButton();
        jButton3 = new JButton();
        jButton4 = new JButton();
        jButton5 = new JButton();
        jButton6 = new JButton();
        jButton7 = new JButton();
        jButton8 = new JButton();
        jButton9 = new JButton();
        jButton10 = new JButton();
        jButton11 = new JButton();
        jButton12 = new JButton();
        jButton13 = new JButton();
        jButton14 = new JButton();
        jLabel3 = new JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Aktueller Spieler:");

        jLabel2.setFont(new Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Punkte:");

        jAktuellerSpielerLabel.setFont(new Font("Arial", 0, 18)); // NOI18N
        jAktuellerSpielerLabel.setText("Name");

        jPunkteSpielerLabel.setFont(new Font("Arial", 0, 18)); // NOI18N
        jPunkteSpielerLabel.setText("0");

        legenButton.setText("Legen");
        legenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legenButtonActionPerformed(evt);
            }
        });

        ziehenButton.setText("Ziehen");
        ziehenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ziehenButtonActionPerformed(evt);
            }
        });

        seppSagenButton.setText("Sepp sagen");
        seppSagenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seppSagenButtonActionPerformed(evt);
            }
        });

        tschauSagenButton.setText("Tschau sagen");
        tschauSagenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tschauSagenButtonActionPerformed(evt);
            }
        });

        jAblageStapelButton.setText(" ");
        jAblageStapelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAblageStapelButtonActionPerformed(evt);
            }
        });

        jButton1.setText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Spielerhand");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jAblageStapelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jPunkteSpielerLabel))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jAktuellerSpielerLabel))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ziehenButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(legenButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(seppSagenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tschauSagenButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton14)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAktuellerSpielerLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jPunkteSpielerLabel))
                        .addGap(120, 120, 120)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(legenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tschauSagenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ziehenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seppSagenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jAblageStapelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ziehenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ziehenButtonActionPerformed
        // TODO add your handling code here:
        if(spiel.ZiehenBestätigen(spiel.getAktuellerSpieler())){

            if(spiel.kartenDeck.getKartenImDeck() <= 1){
                spiel.kartenDeckauffüllen();
            }
                spiel.getAktuellerSpieler().karteHinzufügen(spiel.kartenDeck.karteZiehen());
                if(spiel.getAktuellerSpielerNr()==3){
                    spiel.setAktuellerSpieler(0);
                }else {
                    spiel.setAktuellerSpieler(spiel.getAktuellerSpielerNr() + 1);
                }
                this.setButtonIcons();
                this.setNameAktuellerSpieler();
                this.setSpielerPunkte();

        }else{
        JLabel message = new JLabel("Du kannst eine Karte legen!!");
        message.setFont(new Font("Arial", Font.BOLD, 48));
        JOptionPane.showMessageDialog(null, message);
        }

            
            
    }//GEN-LAST:event_ziehenButtonActionPerformed
    public void setjAblageStapelButton(){
        jAblageStapelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("../images/"+spiel.ablageStapel.getObersteKarte().getSymbol()+ " "+spiel.ablageStapel.getObersteKarte().getZahl()+".gif")));
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(kartenIds.get(0) != null){
          index = 0;
            System.out.println(index);
          ausgewählteKarte = spiel.getAktuellerSpieler().getSpielerHand().get(index);
          
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jAblageStapelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAblageStapelButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jAblageStapelButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(kartenIds.get(1) != null){
            index = 1;

            String karteId = kartenIds.get(1);
         
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            if(kartenIds.get(2) != null){
            index = 2;

            String karteId = kartenIds.get(2);
    
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            if(kartenIds.get(3) != null){
            index = 3;
            String karteId = kartenIds.get(3);
       
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
            if(kartenIds.get(4) != null){
            index = 4;
            String karteId = kartenIds.get(4);
   
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
            if(kartenIds.get(5) != null){
            index = 5;
            String karteId = kartenIds.get(5);
          
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
            if(kartenIds.get(6) != null){
            index = 6;
            String karteId = kartenIds.get(6);
        
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
            if(kartenIds.get(7) != null){
            index = 7;
            String karteId = kartenIds.get(7);
         
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
            if(kartenIds.get(8) != null){
            index = 8;
            String karteId = kartenIds.get(8);
           
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
            if(kartenIds.get(9) != null){
            index = 9;
            String karteId = kartenIds.get(9);
         
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
            if(kartenIds.get(10) != null){
            index = 10;
            String karteId = kartenIds.get(10);
            
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
            if(kartenIds.get(11) != null){
            index = 11;
            String karteId = kartenIds.get(11);
          
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
            if(kartenIds.get(12) != null){
            index = 12;
            String karteId = kartenIds.get(12);
            
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void legenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legenButtonActionPerformed
        // TODO add your handling code here:
        try{
        spiel.spielerZugBestätigen(spiel.getAktuellerSpieler(), spiel.getAktuellerSpieler().getSpielerHand().get(index),index);
        }catch(InvalidZahlSubmssionException ex){
            Logger.getLogger(SpielGUI.class.getName()).log(Level.SEVERE,null, ex);
        }catch(InvalidSymbolSubmssionException ex){
         Logger.getLogger(SpielGUI.class.getName()).log(Level.SEVERE,null, ex);
        }
        this.revalidate();
        this.setButtonIcons();
        this.setjAblageStapelButton();
        this.setNameAktuellerSpieler();
        this.setSpielerPunkte();
        this.back();

    }//GEN-LAST:event_legenButtonActionPerformed

    private void tschauSagenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tschauSagenButtonActionPerformed
        // TODO add your handling code here:
        if(spiel.getAktuellerSpieler().kannTschausagen()){
        spiel.tschauSagen(spiel.getAktuellerSpieler());
        }else{
        JLabel message = new JLabel("Du hast noch zu viele Karten um Tschau sagen zu können");
        message.setFont(new Font("Arial", Font.BOLD, 48));
        JOptionPane.showMessageDialog(null, message);
        }
    }//GEN-LAST:event_tschauSagenButtonActionPerformed

    public void back(){
        if(spiel.istSpielbeendet){
            this.dispose();
            new MenueGUI().setVisible(true);
        }
    }

    private void seppSagenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seppSagenButtonActionPerformed
        // TODO add your handling code here:
         if(spiel.getAktuellerSpieler().kannSeppsagen()){
        spiel.seppSagen(spiel.getAktuellerSpieler());
        }else{
        JLabel message = new JLabel("Du hast noch zu viele Karten um Sepp sagen zu können");
        message.setFont(new Font("Arial", Font.BOLD, 48));
        JOptionPane.showMessageDialog(null, message);
        }
    }//GEN-LAST:event_seppSagenButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jAblageStapelButton;
    private JLabel jAktuellerSpielerLabel;
    private JButton jButton1;
    private JButton jButton10;
    private JButton jButton11;
    private JButton jButton12;
    private JButton jButton13;
    private JButton jButton14;
    private JButton jButton2;
    private JButton jButton3;
    private JButton jButton4;
    private JButton jButton5;
    private JButton jButton6;
    private JButton jButton7;
    private JButton jButton8;
    private JButton jButton9;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private JLabel jPunkteSpielerLabel;
    private JButton legenButton;
    private JButton seppSagenButton;
    private JButton tschauSagenButton;
    private JButton ziehenButton;
    // End of variables declaration//GEN-END:variables
}
